# Generated by Django 3.0.5 on 2020-04-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_accountsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountsettings',
            options={'verbose_name': 'Account settings', 'verbose_name_plural': 'Accounts settings'},
        ),
        migrations.AlterField(
            model_name='accountsettings',
            name='category',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
