# Generated by Django 3.0.5 on 2020-04-17 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_accountsettings_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsettings',
            name='limit_value',
        ),
        migrations.RemoveField(
            model_name='accountsettings',
            name='limit_value_currency',
        ),
        migrations.RemoveField(
            model_name='accountsettings',
            name='report',
        ),
        migrations.RemoveField(
            model_name='accountsettings',
            name='user',
        ),
    ]
