# Generated by Django 3.0.5 on 2020-04-17 11:15

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0006_auto_20200417_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsettings',
            name='category',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finance.Categories'),
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='limit_value',
            field=djmoney.models.fields.MoneyField(currency_choices=(('USD', 'USD'),), decimal_places=2, default=Decimal('100'), default_currency='USD', max_digits=14),
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='limit_value_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'USD')], default='USD', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='report',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
