# Generated by Django 3.0.5 on 2020-04-17 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20200417_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsettings',
            name='user',
        ),
    ]
