# Generated by Django 3.0.5 on 2020-04-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_auto_20200421_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialexpenses',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
