# Generated by Django 3.0.5 on 2020-05-05 06:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0028_auto_20200504_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialexpenses',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
