# Generated by Django 3.0.5 on 2020-05-05 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0029_auto_20200505_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialexpenses',
            name='publish',
        ),
    ]
