# Generated by Django 3.0.5 on 2020-05-05 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0030_remove_financialexpenses_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialexpenses',
            name='publish',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
