# Generated by Django 3.0.5 on 2020-05-05 07:31

from django.db import migrations


def update_value(apps, schema_editor):
    Expenses = apps.get_model("finance", "FinancialExpenses")
    for expense in Expenses.objects.all():
        expense.publish = expense.created
        expense.save()


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0031_financialexpenses_publish'),
    ]

    operations = [
        migrations.RunPython(update_value),
    ]
