# Generated by Django 3.0.5 on 2020-05-12 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0033_auto_20200505_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='user',
        ),
    ]
